builds:
  -
    main: ./cmd/wts/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
brew:
  github:
    owner: g4s8
    name: .tap
  commit_author:
    name: goreleaser
    email: g4s8.public+tap@gmail.com
  homepage: "https://github.com/g4s8/wts"
  folder: Formula
  dependencies:
    - git
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
